// use-reducer/svelte/src/Counter.svelte
<script>
  import { writable } from 'svelte/store'
  const initialState = {count: 0}

  const store = writable(initialState)

  store.increment = () => {
    store.update(state => ({count: state.count + 1}))
  }
  store.decrement = () => {
    store.update(state => ({count: state.count - 1}))
  }
</script>

Count: {$store.count}
<button on:click={() => store.decrement()}>-</button>
<button on:click={() => store.increment()}>+</button>

// use-reducer/react/src/Counter.js
import React, { useReducer } from 'react'

const initialState = {count: 0}

function reducer(state, action) {
  switch (action.type) {
    case 'increment':
      return {count: state.count + 1}
    case 'decrement':
      return {count: state.count - 1}
    default:
      throw new Error()
  }
}

export default function Counter() {
  const [state, dispatch] = useReducer(reducer, initialState)
  return (
    <>
      Count: {state.count}
      <button onClick={() => dispatch({type: 'decrement'})}>-</button>
      <button onClick={() => dispatch({type: 'increment'})}>+</button>
    </>
  )
}
